### ISSUE TITLE
About WHITESPACE priorities

### ISSUE THREAD

**Issue by GalAster** [pest-parser/pest#449]
I want to implement a syntax that only when `expr` and` [`are on the same line it'll be parsed as an `index`, otherwise it will be parsed as an `array`.

```
a[1]   => index
a [
2]      => index
a 
[3]     => array
```

The simplified syntax is similar to:

```js
program = _{SOI ~ expr* ~ EOI}

expr = {prefix? ~ term}
term = {index|array|SYMBOL}
index = {SYMBOL ~ !NEWLINE ~ array}
array = { "[" ~ expr ~"]"}

prefix = {"+"|"-"}

SYMBOL     = @{XID_CONTINUE+}
WHITESPACE = _{NEWLINE|SPACE_SEPARATOR}
COMMENT    = _{"=>" ~ (!NEWLINE ~ ANY)*}
```

But it seems `! NEWLINE` has no effect, it is still skipped as `WHITESPACE`

```yaml
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "1"
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "2"
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "3"
- EOI: ""
```

How should I force Newline here to take effect?

**Comment by CAD97** [comment]
Because `index` is not atomic, it gets "desugared"  to include whitespace. So it desugars to roughly

```
index = ${ SYMBOL ~ WHITESPACE* ~ !NEWLINE ~ WHITESPACE* ~ array }
```

If you want to avoid the implicit WHITESPACE, use a compound atomic (`$`):

```
index = ${ SYMBOL ~ !NEWLINE ~ array }
```

(This may require marking `array` as monatomic (`!`) to re-allow internal WHITESPACE, I don't recall atmoic's propagation rules for compound atomics at the moment.)

-----

As a side note, we chose `SHOUT_CASE` for builtins because it differentiates itself from user-defined rules. You should probably not use `SHOUT_CASE` for your own rules to keep the distinction clear. (Previously, the builtins were `snake_case` like we recommend for user rules, and this caused confusion with the built-in WHITESPACE magical handling.)

**Comment by GalAster** [comment]
Well, it still not work.

```js
index = ${ SYMBOL ~ WHITESPACE* ~ !NEWLINE ~ WHITESPACE* ~ array }
array = { "[" ~ expr ~"]"}
```

```yaml
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "1"
- expr > term > SYMBOL: "a"
- expr > term > array > expr > term > SYMBOL: "2"
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "3"
- EOI: ""
```


---

But this works:

```js
index = ${ SYMBOL ~ (!NEWLINE~SPACE_SEPARATOR*) ~ array }
array = !{ "[" ~ expr ~"]"}
```


```yaml
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "1"
- expr > term > index
  - SYMBOL: "a"
  - array > expr > term > SYMBOL: "2"
- expr > term > SYMBOL: "a"
- expr > term > array > expr > term > SYMBOL: "3"
- EOI: ""
```
