### ISSUE TITLE
Using `pest_derive` without `std` under a workspace fails in Windows.

### ISSUE THREAD

**Issue by Shaddy** [pest-parser/pest#996]
**Describe the bug**

I have a project that requires `no_std`, using following dependencies in `Cargo.toml` 

```TOML
pest = { git = "https://github.com/pest-parser/pest.git", version = "2.7.8", default-features = false }
pest_derive = { git = "https://github.com/pest-parser/pest.git", version = "2.7.8", default-features = false, features = ["not-bootstrap-in-src"] }
```

That fails to locate the bootstrap file under Windows, while in MacOS or Linux is working properly.

**To Reproduce**

- Use pest_derive under a workspace project with no_std.

NOTE: I can provide a project to reproduce the bug if necessary.

**Expected behavior**

`pest_bootstrap.exe` not panicking trying to locate `/meta/src/grammar.pest`

**Additional context**

After debugging generated `pest_bootstrap.exe` I came to the conclusion that the problematic part is the path retrieved by `env!("CARGO_MANIFEST_DIR")` here:

```Rust
    let pest = Path::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../meta/src/grammar.pest"
    ));
```

It seems to prepend `\\?\` to the Path, making it fail when trying to resolve the relative "../meta" path. 

I managed to fix this issue here:

https://github.com/Shaddy/pest/commit/9ea1515c8f747de2444f4704e5e610b7f84b3580

But probably is not the best way to do it, it is just a workaround.
